name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '⏳ Maintenance'
    labels: 
      - 'workflows'
      - 'chore'
      - 'test'
      - 'ci/cd'
      - 'deployments'
  - title: '🛠️ Breaking Changes'
    labels: 
      - 'breaking-change'
      - 'refactor'
  - title: '🧰 Miscellaneous'
    label: 'misc'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' 
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## What's Changed
  $CHANGES
